language: objective-c
osx_image: beta-xcode6.3
xcode_sdk: iphonesimulator8.3 
before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
  - xctool clean test -project SwiftClient.xcodeproj -scheme SwiftClient -sdk iphonesimulator
